name: Generate Bridge Files for macOS
on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

env:
  MAC_RUST_VERSION: "1.81"
  FLUTTER_RUST_BRIDGE_VERSION: "1.80.1"

jobs:
  generate-bridge:
    runs-on: [self-hosted, macOS, ARM64]
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          repository: rustdesk/rustdesk
          ref: ${{ inputs.version != 'master' && format('refs/tags/{0}', inputs.version) || 'master' }}

      - name: Install LLVM and Clang
        run: |
          brew install llvm@15
          echo "LLVM_PATH=/opt/homebrew/opt/llvm@15" >> $GITHUB_ENV

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: ${{ env.MAC_RUST_VERSION }}
          targets: aarch64-apple-darwin
          components: "rustfmt"

      - name: Install flutter_rust_bridge_codegen
        run: |
          cargo install flutter_rust_bridge_codegen --version ${{ env.FLUTTER_RUST_BRIDGE_VERSION }} --features "uuid"

      - name: Generate bridge files
        run: |
          cd flutter
          mkdir -p lib/generated
          mkdir -p macos/Runner
          mkdir -p ios/Runner
          
          ~/.cargo/bin/flutter_rust_bridge_codegen \
            --rust-input ../src/flutter_ffi.rs \
            --dart-output lib/generated/bridge_generated.dart \
            --c-output macos/Runner/bridge_generated.h \
            --dart-decl-output lib/generated/bridge_definitions.dart \
            --class-name RustDesk \
            --llvm-path /opt/homebrew/opt/llvm@15 \
            --skip-add-mod-to-lib \
            --no-build-runner
          
          cp macos/Runner/bridge_generated.h ios/Runner/
          cd ..

      - name: Upload bridge files
        uses: actions/upload-artifact@master
        with:
          name: bridge-artifact-macos
          path: |
            ./flutter/lib/generated/
            ./flutter/macos/Runner/
            ./flutter/ios/Runner/ 