# This yaml shares the build bridge steps with ci and nightly.
name: Build flutter-rust-bridge

on:
  workflow_call:
    inputs:
      version:
        description: 'Rustdesk Version'
        required: true
        type: string

env:
  FLUTTER_VERSION: "3.24.5"  # Updated to match your macOS workflow
  FLUTTER_RUST_BRIDGE_VERSION: "1.80.1"
  RUST_VERSION: "1.75"
  RUST_BACKTRACE: "full"  # Added for better error reporting

jobs:
  generate_bridge:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          repository: rustdesk/rustdesk
          ref: ${{ inputs.version != 'master' && format('refs/tags/{0}', inputs.version) || 'master' }}
          submodules: recursive

      - name: Install prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            clang \
            cmake \
            curl \
            gcc \
            git \
            g++ \
            libclang-dev \
            libgtk-3-dev \
            llvm \
            nasm \
            ninja-build \
            pkg-config \
            wget

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: ${{ env.RUST_VERSION }}
          components: "rustfmt"

      - name: Install flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version: ${{ env.FLUTTER_VERSION }}
          cache: true

      - name: Setup Flutter
        run: |
          flutter doctor -v
          flutter pub global activate melos
          flutter config --no-analytics

      - name: Install flutter rust bridge deps
        shell: bash
        run: |
          cargo install flutter_rust_bridge_codegen --version ${{ env.FLUTTER_RUST_BRIDGE_VERSION }} --features "uuid"
          cd flutter
          flutter clean
          flutter pub get
          cd ..

      - name: Generate bridge files
        run: |
          mkdir -p flutter/lib/generated
          ~/.cargo/bin/flutter_rust_bridge_codegen \
            --rust-input ./src/flutter_ffi.rs \
            --dart-output ./flutter/lib/generated/bridge_generated.dart \
            --c-output ./flutter/macos/Runner/bridge_generated.h \
            --dart-decl-output ./flutter/lib/generated/bridge_definitions.dart \
            --class-name RustDesk
          
          cp ./flutter/macos/Runner/bridge_generated.h ./flutter/ios/Runner/bridge_generated.h

      - name: Upload Artifact
        uses: actions/upload-artifact@master
        with:
          name: bridge-artifact
          path: |
            ./src/bridge_generated.rs
            ./src/bridge_generated.io.rs
            ./flutter/lib/generated/bridge_generated.dart
            ./flutter/lib/generated/bridge_definitions.dart
            ./flutter/macos/Runner/bridge_generated.h
            ./flutter/ios/Runner/bridge_generated.h
