# This yaml shares the build bridge steps with ci and nightly.
name: Build flutter-rust-bridge

on:
  workflow_call:
    inputs:
      version:
        description: 'Rustdesk Version'
        required: true
        type: string

env:
  FLUTTER_VERSION: "3.24.5"
  FLUTTER_RUST_BRIDGE_VERSION: "1.80.1"
  RUST_VERSION: "1.75"
  RUST_BACKTRACE: "full"
  DART_VERSION: "3.5.4"

jobs:
  generate_bridge:
    runs-on: ubuntu-20.04
    steps:
      # Previous steps remain the same until Flutter setup

      - name: Setup Flutter
        run: |
          flutter doctor -v
          flutter pub global activate melos
          flutter config --no-analytics
          dart pub global activate build_runner
          dart pub global activate freezed
          
      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ env.DART_VERSION }}

      - name: Install flutter rust bridge deps
        shell: bash
        run: |
          cargo install flutter_rust_bridge_codegen --version ${{ env.FLUTTER_RUST_BRIDGE_VERSION }} --features "uuid"
          cd flutter
          flutter clean
          flutter pub get
          flutter pub add build_runner --dev
          flutter pub add freezed_annotation
          flutter pub add freezed --dev
          cd ..

      - name: Generate bridge files
        run: |
          mkdir -p flutter/lib/generated
          export PATH="$PATH:$HOME/.pub-cache/bin"
          ~/.cargo/bin/flutter_rust_bridge_codegen \
            --rust-input ./src/flutter_ffi.rs \
            --dart-output ./flutter/lib/generated/bridge_generated.dart \
            --c-output ./flutter/macos/Runner/bridge_generated.h \
            --dart-decl-output ./flutter/lib/generated/bridge_definitions.dart \
            --class-name RustDesk
          
          cd flutter
          dart run build_runner build --delete-conflicting-outputs
          cd ..
          
          cp ./flutter/macos/Runner/bridge_generated.h ./flutter/ios/Runner/bridge_generated.h

      # Rest of the file remains the same
