name: Build flutter-rust-bridge for macOS
on:
  workflow_call:
    inputs:
      version:
        description: 'Rustdesk Version'
        required: true
        type: string

env:
  FLUTTER_VERSION: "3.24.5"
  FLUTTER_RUST_BRIDGE_VERSION: "1.80.1"
  RUST_VERSION: "1.75"

jobs:
  generate_bridge:
    runs-on: self-hosted
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          repository: rustdesk/rustdesk
          ref: ${{ inputs.version != 'master' && format('refs/tags/{0}', inputs.version) || 'master' }}
          submodules: recursive

      - name: Install build runtime (macOS)
        run: |
          brew install llvm create-dmg nasm cmake gcc wget ninja
          if command -v pkg-config &>/dev/null; then
              echo "pkg-config is already installed"
          else
              brew install pkg-config
          fi

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: ${{ env.RUST_VERSION }}
          targets: aarch64-apple-darwin
          components: "rustfmt"

      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: bridge-macos

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: ${{ env.FLUTTER_VERSION }}
          cache: true

      - name: Verify Flutter installation
        run: |
          flutter doctor -v
          which flutter
          which dart
          echo $PATH

      - name: Install flutter_rust_bridge_codegen
        run: |
          export PATH="$PATH:$HOME/.pub-cache/bin"
          cargo install flutter_rust_bridge_codegen --version ${{ env.FLUTTER_RUST_BRIDGE_VERSION }} --features "uuid"

      - name: Install flutter rust bridge deps
        shell: bash
        run: |
          cd flutter
          flutter clean
          sed -i '' 's/extended_text: 14.0.0/extended_text: 13.0.0/' pubspec.yaml
          flutter pub get
          cd lib
          find . -name "*.dart" | xargs -I{} sed -i '' 's/textScaler: TextScaler.linear(\(.*\)),/textScaleFactor: \1,/g' {}
          cd ..
          flutter pub add build_runner --dev
          flutter pub add freezed_annotation
          flutter pub add freezed --dev
          flutter pub add ffigen:^8.0.0 --dev
          flutter pub add flutter_rust_bridge
          flutter pub get
          mkdir -p lib/generated
          cd ..

      - name: Run flutter rust bridge
        env:
          RUST_BACKTRACE: "full"
          FLUTTER_ROOT: "/Users/venimk/actions-runner/_work/_tool/flutter/stable-3.24.5-arm64"
          DART_SDK: "/Users/venimk/actions-runner/_work/_tool/flutter/stable-3.24.5-arm64/bin/cache/dart-sdk"
        run: |
          mkdir -p flutter/lib/generated
          mkdir -p flutter/macos/Runner
          mkdir -p flutter/ios/Runner
          
          cd flutter
          # Set up environment
          export PATH="$FLUTTER_ROOT/bin:$PATH"
          export PATH="$DART_SDK/bin:$PATH"
          export PATH="$PATH:$HOME/.pub-cache/bin"
          
          # Verify environment
          echo "Flutter root: $FLUTTER_ROOT"
          echo "Dart SDK: $DART_SDK"
          echo "PATH: $PATH"
          flutter --version
          dart --version
          
          # Generate bridge code
          flutter_rust_bridge_codegen \
            --rust-input ../src/flutter_ffi.rs \
            --dart-output lib/generated/bridge_generated.dart \
            --c-output macos/Runner/bridge_generated.h \
            --dart-decl-output lib/generated/bridge_definitions.dart \
            --class-name RustDesk
          
          # Setup build environment
          flutter pub get
          flutter pub global activate build_runner
          
          # Run build_runner using full path to dart
          "$DART_SDK/bin/dart" pub global run build_runner build --delete-conflicting-outputs
          
          cp macos/Runner/bridge_generated.h ios/Runner/
          cd ..

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: bridge-artifact
          path: |
            ./src/bridge_generated.rs
            ./src/bridge_generated.io.rs
            ./flutter/lib/generated_bridge.dart
            ./flutter/lib/generated_bridge.freezed.dart
            ./flutter/macos/Runner/bridge_generated.h
            ./flutter/ios/Runner/bridge_generated.h
