name: Custom macOS Client Generator
run-name: Custom macOS Client Generator
on: 
  workflow_dispatch:
    inputs:
      server:
        description: 'Rendezvous Server'
        required: true
        default: ''
        type: string
      key:
        description: 'Public Key'
        required: true
        default: ''
        type: string
      apiServer:
        description: 'API Server'
        required: true
        default: ''
        type: string
      custom:
        description: "Custom JSON"
        required: true
        default: ''
        type: string
      uuid:
        description: "uuid of request"
        required: true
        default: ''
        type: string
      iconlink:
        description: "icon link"
        required: false
        default: 'false'
        type: string
      logolink:
        description: "logo link"
        required: false
        default: 'false'
        type: string
      appname:
        description: "app name"
        required: true
        default: 'rustdesk'
        type: string
      filename:
        description: "Filename"
        required: true
        default: 'rustdesk'
        type: string
      extras:
        description: "Extra options in JSON format"
        required: true
        default: '{}'
        type: string

env:
  FLUTTER_VERSION: "3.24.5"
  RUST_VERSION: "1.81"
  MAC_RUST_VERSION: "1.81"
  MACOS_MIN_VER: "12.3"
  STATUS_URL: "${{ format('https://api.rustdesk.com/status/{0}', inputs.uuid) }}"
  FLUTTER_RUST_BRIDGE_VERSION: "1.63.0"

jobs:
  generate-bridge:
    uses: ./.github/workflows/bridge.yml
    with:
      version: ${{ fromJson(inputs.extras).version }}

  build-macos:
    needs: [generate-bridge]
    strategy:
      matrix:
        include:
          - arch: x86_64
            runner: macos-13
            target: x86_64-apple-darwin
          - arch: arm64
            runner: macos-14
            target: aarch64-apple-darwin
    
    name: Build macOS (${{ matrix.arch }})
    runs-on: ${{ matrix.runner }}
    
    steps:
      - name: Export GitHub Actions cache environment variables
        uses: actions/github-script@v6
        with:
          script: |
            core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          brew install llvm create-dmg nasm cmake gcc wget ninja pkg-config

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: ${{ env.MAC_RUST_VERSION }}
          targets: ${{ matrix.target }}

      - name: Restore bridge files
        uses: actions/download-artifact@master
        with:
          name: bridge-artifact
          path: ./

      - name: Set minimum macOS version
        run: |
          sed -i -e "s/MACOSX_DEPLOYMENT_TARGET\=[0-9]*.[0-9]*/MACOSX_DEPLOYMENT_TARGET=${MACOS_MIN_VER}/" build.py
          sed -i -e "s/platform :osx, '.*'/platform :osx, '${MACOS_MIN_VER}'/" flutter/macos/Podfile
          sed -i -e "s/osx_minimum_system_version = \"[0-9]*.[0-9]*\"/osx_minimum_system_version = \"${MACOS_MIN_VER}\"/" Cargo.toml
          sed -i -e "s/MACOSX_DEPLOYMENT_TARGET = [0-9]*.[0-9]*;/MACOSX_DEPLOYMENT_TARGET = ${MACOS_MIN_VER};/" flutter/macos/Runner.xcodeproj/project.pbxproj

      - name: cargo.toml, runner.rc name, en.rs
        continue-on-error: true
        shell: bash
        run: |
          cp ./Cargo.toml ./Cargo.toml.bak
          sed -i -e "s/name = \"rustdesk\"/name = \"${{ inputs.appname }}\"/" ./Cargo.toml
          sed -i -e "s/RustDesk/${{ inputs.appname }}/" ./src/lang/en.rs
          sed -i -e "s/RustDesk/${{ inputs.appname }}/" ./flutter/macos/Runner/Info.plist
          sed -i -e "s/RustDesk/${{ inputs.appname }}/" ./flutter/macos/Runner.xcodeproj/project.pbxproj

      - name: icon stuff
        if: ${{ inputs.iconlink != 'false' }}
        continue-on-error: true
        shell: bash
        run: |
          mv ./res/icon.ico ./res/icon.ico.bak
          mv ./res/icon.png ./res/icon.png.bak
          mv ./res/tray-icon.ico ./res/tray-icon.ico.bak
          wget -O ./res/icon.png ${{ inputs.iconlink }}
          wget -O ./res/icon.ico ${{ inputs.iconlink }}
          wget -O ./res/tray-icon.ico ${{ inputs.iconlink }}
          cp ./res/icon.png ./flutter/macos/Runner/Assets.xcassets/AppIcon.appiconset/app_icon_1024.png
          cp ./res/icon.png ./flutter/macos/Runner/Assets.xcassets/AppIcon.appiconset/app_icon_128.png
          cp ./res/icon.png ./flutter/macos/Runner/Assets.xcassets/AppIcon.appiconset/app_icon_16.png
          cp ./res/icon.png ./flutter/macos/Runner/Assets.xcassets/AppIcon.appiconset/app_icon_256.png
          cp ./res/icon.png ./flutter/macos/Runner/Assets.xcassets/AppIcon.appiconset/app_icon_32.png
          cp ./res/icon.png ./flutter/macos/Runner/Assets.xcassets/AppIcon.appiconset/app_icon_512.png
          cp ./res/icon.png ./flutter/macos/Runner/Assets.xcassets/AppIcon.appiconset/app_icon_64.png

      - name: logo stuff
        if: ${{ inputs.logolink != 'false' }}
        continue-on-error: true
        shell: bash
        run: |
          mv ./res/logo.ico ./res/logo.ico.bak
          mv ./res/logo.png ./res/logo.png.bak
          wget -O ./res/logo.png ${{ inputs.logolink }}
          wget -O ./res/logo.ico ${{ inputs.logolink }}

      - name: Import the codesign cert
        if: env.MACOS_P12_BASE64 != ''
        uses: apple-actions/import-codesign-certs@v1
        with:
          p12-file-base64: ${{ secrets.MACOS_P12_BASE64 }}
          p12-password: ${{ secrets.MACOS_P12_PASSWORD }}
          keychain: rustdesk

      - name: Check sign and import sign key
        if: env.MACOS_P12_BASE64 != ''
        run: |
          security default-keychain -s rustdesk.keychain
          security find-identity -v

      - name: Import notarize key
        if: env.MACOS_P12_BASE64 != ''
        uses: timheuer/base64-to-file@v1.2
        with:
          fileName: rustdesk.json
          fileDir: ${{ github.workspace }}
          encodedString: ${{ secrets.MACOS_NOTARIZE_JSON }}

      - name: Install rcodesign tool
        if: env.MACOS_P12_BASE64 != ''
        shell: bash
        run: |
          pushd /tmp
          wget https://github.com/indygreg/apple-platform-rs/releases/download/apple-codesign%2F0.22.0/apple-codesign-0.22.0-macos-universal.tar.gz
          tar -zxvf apple-codesign-0.22.0-macos-universal.tar.gz
          mv apple-codesign-0.22.0-macos-universal/rcodesign /usr/local/bin
          popd

      - name: Install build runtime
        run: |
          brew install llvm create-dmg nasm cmake gcc wget ninja pkg-config

      - name: Install flutter rust bridge deps
        shell: bash
        run: |
          sed -i '' 's/3.1.0/2.17.0/g' flutter/pubspec.yaml;
          cargo install flutter_rust_bridge_codegen --version ${{ env.FLUTTER_RUST_BRIDGE_VERSION }} --features "uuid"
          pushd flutter && sed -i -e 's/extended_text: 14.0.0/extended_text: 13.0.0/g' pubspec.yaml && flutter pub get && popd
          ~/.cargo/bin/flutter_rust_bridge_codegen --rust-input ./src/flutter_ffi.rs --dart-output ./flutter/lib/generated_bridge.dart --c-output ./flutter/macos/Runner/bridge_generated.h

      - name: Build Generator
        env:
          RENDEZVOUS_SERVER: ${{ inputs.server }}
          RS_PUB_KEY: ${{ inputs.key }}
          API_SERVER: ${{ inputs.apiServer }}
          CUSTOM_JSON: ${{ inputs.custom }}
        run: |
          ./build.py --flutter --hwcodec

      - name: Create DMG
        run: |
          # Patch create-dmg to give more attempts to unmount image
          CREATE_DMG="$(command -v create-dmg)"
          CREATE_DMG="$(readlink -f "$CREATE_DMG")"
          sed -i -e 's/MAXIMUM_UNMOUNTING_ATTEMPTS=3/MAXIMUM_UNMOUNTING_ATTEMPTS=7/' "$CREATE_DMG"
          create-dmg --icon "${{ inputs.appname }}.app" 200 190 --hide-extension "${{ inputs.appname }}.app" --window-size 800 400 --app-drop-link 600 185 ${{ inputs.filename }}-${{ matrix.arch }}.dmg ./flutter/build/macos/Build/Products/Release/${{ inputs.appname }}.app

      - name: Code Sign (if credentials available)
        if: env.MACOS_P12_BASE64 != ''
        run: |
          # Unlock keychain
          security default-keychain -s rustdesk.keychain
          security unlock-keychain -p ${{ secrets.MACOS_P12_PASSWORD }} rustdesk.keychain
          # Sign app and DMG
          codesign --force --options runtime -s "${{ secrets.MACOS_CODESIGN_IDENTITY }}" --deep --strict ./flutter/build/macos/Build/Products/Release/${{ inputs.appname }}.app -vvv
          create-dmg --icon "${{ inputs.appname }}.app" 200 190 --hide-extension "${{ inputs.appname }}.app" --window-size 800 400 --app-drop-link 600 185 ${{ inputs.filename }}-${{ matrix.arch }}.dmg ./flutter/build/macos/Build/Products/Release/${{ inputs.appname }}.app
          codesign --force --options runtime -s "${{ secrets.MACOS_CODESIGN_IDENTITY }}" --deep --strict ${{ inputs.filename }}-${{ matrix.arch }}.dmg -vvv
          # Notarize the DMG
          rcodesign notary-submit --api-key-path ${{ github.workspace }}/rustdesk.json --staple ${{ inputs.filename }}-${{ matrix.arch }}.dmg

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.filename }}-macos-${{ matrix.arch }}
          path: ${{ inputs.filename }}-${{ matrix.arch }}.dmg

      - name: Report Status
        if: always()
        uses: fjogeleit/http-request-action@v1
        with:
          url: ${{ env.STATUS_URL }}
          method: 'POST'
          data: '{"status": "${{ job.status }}", "job_type": "build", "os": "macos-${{ matrix.arch }}", "filename": "${{ inputs.filename }}-${{ matrix.arch }}.dmg"}'
