name: build RustDeskTempTopMostWindow

on:
  workflow_call:
    inputs:
      upload-artifact:
        type: boolean
        default: true
      target:
        description: 'Target'
        required: true
        type: string
        default: 'windows-2022'
      configuration:
        description: 'Configuration'
        required: true
        type: string
        default: 'Release'
      platform:
        description: 'Platform'
        required: true
        type: string
        default: 'x64'
      target_version:
        description: 'TargetVersion'
        required: true
        type: string
        default: 'Windows10'

env:
  project_path: WindowInjection/WindowInjection.vcxproj

jobs:
  build-RustDeskTempTopMostWindow:
    runs-on: ${{ inputs.target }}
    strategy:
      fail-fast: false
    env:
      build_output_dir: RustDeskTempTopMostWindow/WindowInjection/${{ inputs.platform }}/${{ inputs.configuration }}
    steps:
      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Download the source code
        run: |
          if (Test-Path "RustDeskTempTopMostWindow") {
            Remove-Item -Recurse -Force "RustDeskTempTopMostWindow"
          }
          git clone https://github.com/rustdesk-org/RustDeskTempTopMostWindow RustDeskTempTopMostWindow

      - name: Build the project
        run: |
          cd RustDeskTempTopMostWindow
          msbuild ${{ env.project_path }} -p:Configuration=${{ inputs.configuration }} -p:Platform=${{ inputs.platform }} /p:TargetVersion=${{ inputs.target_version }}

      - name: Archive build artifacts
        uses: actions/upload-artifact@master
        if: ${{ inputs.upload-artifact }}
        with:
          name: topmostwindow-artifacts
          path: |
            ./${{ env.build_output_dir }}/WindowInjection.dll
